# language.py

TRANSLATIONS = {
    'vi': {
        'thinking': "✍️",
        'searching': "🌐 Đang tìm kiếm trên web...",
        'service_unavailable': "Dịch vụ không phản hồi, vui lòng thử lại sau...",
        'wait_message': "⏳ Vui lòng đợi 10 giây trước khi gửi tin nhắn tiếp theo.",
        'ask_prompt': "❗ Bạn cần nhập câu hỏi sau lệnh /ask.",
        'chat_reset': "🔄 Đoạn chat đã được đặt lại. Hãy bắt đầu lại câu hỏi mới.",
        'model_switch': "⭕ Một số mô hình AI có thể không khả dụng do hạn chế quyền truy cập API. Vui lòng thử chuyển đổi sang mô hình khác nếu gặp vấn đề😉\n\n🔄 Chọn mô hình AI",
        'model_switched': "✅ Đã chuyển sang {}",
        'invalid_model': "❌ Mô hình không hợp lệ",
        'model_switched_reset': "✅ Đã chuyển đổi mô hình AI sang {}.\n\n🔄 Đoạn chat đã được đặt lại. Hãy bắt đầu lại câu hỏi mới nhé😉",
        'training_not_supported': "❌ Mô hình lolillm-0.1-beta không hỗ trợ lệnh training từ người dùng.",
        'training_prompt': "❗ Bạn cần nhập câu đào tạo bằng cách /training + câu đào tạo (Không giới hạn kí tự nhưng khuyên nên dùng tầm dưới 200 kí tự là ok)\n\nCâu đào tạo hiện tại:\n\n ",
        'no_training': "Chưa có câu đào tạo nào",
        'training_updated': "✅ Đã cập nhật câu đào tạo\n \"{}\"",
        'enter_question': "❗ Bạn cần nhập câu hỏi.",
        'processing_image': "🖼️ Đang xử lý ảnh...",
        'image_description': "🖼️ Mô tả ảnh:\n\n{}",
        'checking_ip': "🔍 Đang kiểm tra IP...",
        'ip_info_unavailable': "❌ Không thể lấy thông tin cho địa chỉ IP này.",
        'welcome_message': "👋 Xin chào, {}! \n🤖 Tôi là Hydra, một AI siêu vjp được tạo ra bởi Wyn. \n💡 Tôi có thể giúp bạn trả lời nhiều câu hỏi khác nhau, đa lĩnh vực. \n❓ Hãy hỏi tôi bất cứ điều gì, tôi sẽ cố gắng để trả lời cho bạn nhé 🥰",
    },
    'en': {
        'thinking': "✍️",
        'searching': "🌐 Searching the web...",
        'service_unavailable': "The service is not responding, please try again later...",
        'wait_message': "⏳ Please wait 10 seconds before sending another message.",
        'ask_prompt': "❗ You need to enter a question after the /ask command.",
        'chat_reset': "🔄 The chat has been reset. Start a new question.",
        'model_switch': "⭕ Some AI models may not be available due to API access restrictions. Please try switching to another model if you encounter issues😉\n\n🔄 Select AI model",
        'model_switched': "✅ Switched to {}",
        'invalid_model': "❌ Invalid model",
        'model_switched_reset': "✅ Switched AI model to {}.\n\n🔄 The chat has been reset. Start a new question😉",
        'training_not_supported': "❌ The lolillm-0.1-beta model does not support user training commands.",
        'training_prompt': "❗ You need to enter a training instruction using /training + instruction (No character limit, but recommended to use about 200 characters or less)\n\nCurrent training instruction:\n\n ",
        'no_training': "No training instruction set",
        'training_updated': "✅ Updated training instruction\n \"{}\"",
        'enter_question': "❗ You need to enter a question.",
        'processing_image': "🖼️ Processing image...",
        'image_description': "🖼️ Image description:\n\n{}",
        'checking_ip': "🔍 Checking IP...",
        'ip_info_unavailable': "❌ Unable to retrieve information for this IP address.",
        'welcome_message': "👋 Hello, {}! \n🤖 I'm Hydra, a super cool AI created by Wyn. \n💡 I can help you answer various questions across different fields. \n❓ Ask me anything, and I'll try my best to answer! 🥰",
    },
    'zh': {
        'thinking': "✍️",
        'searching': "🌐 正在搜索网络...",
        'service_unavailable': "服务无响应，请稍后再试...",
        'wait_message': "⏳ 请等待10秒后再发送下一条消息。",
        'ask_prompt': "❗ 你需要在 /ask 命令后输入问题。",
        'chat_reset': "🔄 聊天已重置。开始新的问题吧。",
        'model_switch': "⭕ 由于API访问限制，某些AI模型可能不可用。如果遇到问题，请尝试切换到其他模型😉\n\n🔄 选择AI模型",
        'model_switched': "✅ 已切换到 {}",
        'invalid_model': "❌ 无效的模型",
        'model_switched_reset': "✅ AI模型已切换到 {}。\n\n🔄 聊天已重置。开始新的问题吧😉",
        'training_not_supported': "❌ lolillm-0.1-beta 模型不支持用户训练命令。",
        'training_prompt': "❗ 你需要使用 /training + 指令来输入训练指令（无字符限制，但建议使用200个字符左右）\n\n当前训练指令：\n\n ",
        'no_training': "尚未设置训练指令",
        'training_updated': "✅ 已更新训练指令\n \"{}\"",
        'enter_question': "❗ 你需要输入一个问题。",
        'processing_image': "🖼️ 正在处理图片...",
        'image_description': "🖼️ 图片描述：\n\n{}",
        'checking_ip': "🔍 正在检查IP...",
        'ip_info_unavailable': "❌ 无法获取此IP地址的信息。",
        'welcome_message': "👋 你好，{}！\n🤖 我是Hydra，一个由Wyn创造的超级酷的AI。\n💡 我可以帮你回答各种不同领域的问题。\n❓ 问我任何问题，我会尽力回答！🥰",
    },
    'ko': {
        'thinking': "✍️",
        'searching': "🌐 웹 검색 중...",
        'service_unavailable': "서비스가 응답하지 않습니다. 나중에 다시 시도해 주세요...",
        'wait_message': "⏳ 다음 메시지를 보내기 전에 10초 동안 기다려 주세요.",
        'ask_prompt': "❗ /ask 명령 뒤에 질문을 입력해야 합니다.",
        'chat_reset': "🔄 채팅이 초기화되었습니다. 새로운 질문을 시작하세요.",
        'model_switch': "⭕ API 접근 제한으로 인해 일부 AI 모델을 사용할 수 없을 수 있습니다. 문제가 발생하면 다른 모델로 전환해 보세요😉\n\n🔄 AI 모델 선택",
        'model_switched': "✅ {}(으)로 전환되었습니다",
        'invalid_model': "❌ 잘못된 모델",
        'model_switched_reset': "✅ AI 모델이 {}(으)로 전환되었습니다.\n\n🔄 채팅이 초기화되었습니다. 새로운 질문을 시작하세요😉",
        'training_not_supported': "❌ lolillm-0.1-beta 모델은 사용자 훈련 명령을 지원하지 않습니다.",
        'training_prompt': "❗ /training + 지시사항을 사용하여 훈련 지시사항을 입력해야 합니다 (문자 제한 없음, 하지만 200자 정도 사용 권장)\n\n현재 훈련 지시사항:\n\n ",
        'no_training': "설정된 훈련 지시사항 없음",
        'training_updated': "✅ 훈련 지시사항 업데이트됨\n \"{}\"",
        'enter_question': "❗ 질문을 입력해야 합니다.",
        'processing_image': "🖼️ 이미지 처리 중...",
        'image_description': "🖼️ 이미지 설명:\n\n{}",
        'checking_ip': "🔍 IP 확인 중...",
        'ip_info_unavailable': "❌ 이 IP 주소에 대한 정보를 검색할 수 없습니다.",
        'welcome_message': "👋 안녕하세요, {}님! \n🤖 저는 Wyn이 만든 초cool한 AI, Hydra입니다. \n💡 다양한 분야의 질문에 답변해 드릴 수 있어요. \n❓ 무엇이든 물어보세요, 최선을 다해 답변하겠습니다! 🥰",
    },
    'ar': {
        'thinking': "✍️",
        'searching': "🌐 جاري البحث على الإنترنت...",
        'service_unavailable': "الخدمة لا تستجيب، يرجى المحاولة مرة أخرى لاحقًا...",
        'wait_message': "⏳ يرجى الانتظار 10 ثوانٍ قبل إرسال رسالة أخرى.",
        'ask_prompt': "❗ تحتاج إلى إدخال سؤال بعد الأمر /ask.",
        'chat_reset': "🔄 تم إعادة تعيين المحادثة. ابدأ سؤالًا جديدًا.",
        'model_switch': "⭕ قد لا تتوفر بعض نماذج الذكاء الاصطناعي بسبب قيود الوصول إلى واجهة برمجة التطبيقات. يرجى محاولة التبديل إلى نموذج آخر إذا واجهت مشاكل😉\n\n🔄 اختر نموذج الذكاء الاصطناعي",
        'model_switched': "✅ تم التبديل إلى {}",
        'invalid_model': "❌ نموذج غير صالح",
        'model_switched_reset': "✅ تم تبديل نموذج الذكاء الاصطناعي إلى {}.\n\n🔄 تم إعادة تعيين المحادثة. ابدأ سؤالًا جديدًا😉",
        'training_not_supported': "❌ نموذج lolillm-0.1-beta لا يدعم أوامر تدريب المستخدم.",
        'training_prompt': "❗ تحتاج إلى إدخال تعليمات التدريب باستخدام /training + التعليمات (بدون حد للأحرف، ولكن يُنصح باستخدام حوالي 200 حرف أو أقل)\n\nتعليمات التدريب الحالية:\n\n ",
        'no_training': "لم يتم تعيين تعليمات تدريب",
        'training_updated': "✅ تم تحديث تعليمات التدريب\n \"{}\"",
        'enter_question': "❗ تحتاج إلى إدخال سؤال.",
        'processing_image': "🖼️ جاري معالجة الصورة...",
        'image_description': "🖼️ وصف الصورة:\n\n{}",
        'checking_ip': "🔍 جاري فحص عنوان IP...",
        'ip_info_unavailable': "❌ تعذر الحصول على معلومات لعنوان IP هذا.",
        'welcome_message': "👋 مرحبًا، {}!\n🤖 أنا Hydra، ذكاء اصطناعي رائع تم إنشاؤه بواسطة Wyn.\n💡 يمكنني مساعدتك في الإجابة على أسئلة متنوعة في مجالات مختلفة.\n❓ اسألني أي شيء، وسأحاول الإجابة بأفضل ما لدي! 🥰",
    }
}

def get_text(lang, key):
    return TRANSLATIONS.get(lang, TRANSLATIONS['en']).get(key, TRANSLATIONS['en'][key])