name: Run Multiple Scripts

on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update and install Python dependencies
        run: |
          sudo apt update
          pip install -r requirements.txt

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'

      - name: Update and install Go dependencies
        run: |
          go mod download

      - name: Run ipconverter.py
        run: python ipconverter.py

      - name: Run scan.go
        run: go run scan.go

      - name: Run brute.py
        run: python brute.py